### ISSUE TITLE
Missing attachment data:     Missing files: 2143

### ISSUE THREAD

**Issue by 2600box** [ReagentX/imessage-exporter#110]
Hello, your tool is awesome. I have a query about this diagnostic message.

It says:
```
Missing attachment data:
    Missing files: 2143
```

How can I find out what is missing? 
I guess it is relevant to what I see in the html files I see they reference correctly an image, but does not load, though I can open it separately.

Typical file looks like `-rw-r--r--  1 User  staff  1138524 15 Apr 22:36 /Users/User/Library/Messages/Attachments/f4/04/at_0_A5198FA1-01AE-42FE-9DEA-BD570E80016C/IMG_2669.PNG`

```
~ ./imessage-exporter-x86_64-apple-darwin -d
Building cache...
[1/4] Caching chats...
[2/4] Caching chatrooms...
[3/4] Caching participants...
[4/4] Caching reactions...
Cache built!

iMessage Database Diagnostics

Contacts with more than one ID: 25
Messages not associated with a chat: 23
Missing attachment data:
    Missing files: 2143
Duplicated contacts: 127
Duplicated chats: 2
Done!
```

**Comment by ReagentX** [comment]
That missing files message means there were files referenced in the database that do not exist on the disk. Since they don't exist, `imessage-exporter` cannot copy them to your exports.

Currently there isn't a feature to see which attachments are missing. In exports, missing files are noted:

https://github.com/ReagentX/imessage-exporter/blob/9c5f185dc171857323fae089bbad1702fec96df2/imessage-exporter/src/exporters/html.rs#L274-L279
