### ISSUE TITLE
Incorrect dates and missing attachments

### ISSUE THREAD

**Issue by charlesalec** [ReagentX/imessage-exporter#133]
Hello,

Before I go into details, I have to stress how awesome this project is. It's been something that's been on the back of my mind for a decade, to find out someone has single-handedly done this is amazing. 

About my issue: I've successfully exported the messages (just using the no copy parameter, and the path to the .db file).
When I open the HTML files, I get the date as Jan 01, 2001 1:00:00 AM, and attachments show the file not found icon. Additionally the contacts are given as numbers, rather than the names of the contacts, but I assume that's how they're stored in the db.

As a note: this is a very old .db file, it was used from 2014 to 2016, so maybe that has an influence.

EDIT: for the attachments, seems like it's looking for them in /Users/Library/Messages, instead of in the path I provide. 

EDIT2: It seems that it's referencing phantom attachments in the .db file, and that they don't exist in the attachments folder, not sure why that is, will investigate.. 

Any help appreciated, cheers!

**Comment by ReagentX** [comment]
The date issue stems from older tables using a different [epoch](https://docs.rs/imessage-database/latest/imessage_database/util/dates/fn.get_offset.html) for timestamps in the messages table. This project only targets the current version (noted in the [docs](https://github.com/ReagentX/imessage-exporter/blob/develop/docs/features.md#targeted-versions)).

For info on contact details, see #62.

The file paths `imessage-exporter` looks at are stored in the iMessage database. If the file isn't at the specified location there isn't really anything we can do.

**Comment by michaelnow-byteme** [comment]
if the file isn't at the specified location, it seems like the app (wonderful, btw - leaps & bounds the best option) could easily expect the Attachments folder to be located in the same relative path as the chat.db (../Attachments since chat.db is at the same level as Attachments) or an additional parameter could be accepted for Attachments path. Also, it's open source, so each of us could me it behave the way we wish. (THANK YOU FOR THAT, BTW!)
