### ISSUE TITLE
Invalid column type Null at index: 5, name: handle_id

### ISSUE THREAD

**Issue by jrollinson** [ReagentX/imessage-exporter#148]
Hello,

When exporting from two separate iOS backups of different phones (but with some shared history), I receive the following error:

```
Unable to start: Failed to parse row: Invalid column type Null at index: 5, name: handle_id
```

This causes the job to die.

**Comment by ReagentX** [comment]
Right now that column is not considered optional, hence the crash:

https://github.com/ReagentX/imessage-exporter/blob/c73bc4d666da3a543708b553c9106acf89454e81/imessage-database/src/tables/messages.rs#L80


The column is `INTEGER | DEFAULT 0` so I am surprised it can be `NULL`. The fix is to give this a default: 

https://github.com/ReagentX/imessage-exporter/blob/c73bc4d666da3a543708b553c9106acf89454e81/imessage-database/src/tables/messages.rs#L110
