### ISSUE TITLE
Support shared locations

### ISSUE THREAD

**Issue by podviaznikov** [ReagentX/imessage-exporter#169]
iMessage now supports sharing location. Is it possible to add support for such messages?

**Comment by ReagentX** [comment]
If this is about iOS 17's new location messages, those are live-updating balloons that show the current location of the user: https://www.macrumors.com/how-to/share-location-messages-ios/

Since these exports occur after the fact, I need to investigate what data is stored there. It might make sense to just render these as announcement messages like existing location sharing stop/start announcements.

I added this to #127.

**Comment by podviaznikov** [comment]
thank you for trying to add this.

**Comment by ReagentX** [comment]
This is already supported in the current version of `imessage-exporter`.

**Comment by podviaznikov** [comment]
I see "Find My" message. but it has not actual location. It also adds query parameter to the link

```

href="?FindMyMessagePayloadVersionKey=v0&FindMyMessagePayloadZippedDataKey=VZDNTsMwEITfZc9JtP63c2sLOXHiDazUpRZpXGIHCaK+OxupgbKnlcYzO/4WiLmb0uU15DAeoT35IYcK4hhL9MNL6n2JaYR2gXOa4ncaix92fT9Pvv+CVqgKBnpR5mOAVolGSIvoHHIjUdsK+jRPmSSsIF9DoAM1I0sa3+6eWjdcCG0VY6idRktyiZeQi79coWXaGcOUQ9Eg09Iadg/660DRn2EqsX8sxijWkcMazTkaFBX4YetJmpKSMy4kE2iV23o+hN4qeI8rkAXy2U9hXTZSHzPV+0V1JMvGiBzhtLILA4UsN5p/3zHMSbQGbaMMV0iAIp0A1NixJ2XrvdCuls+dqN3uIGuGB75TZi+FM3D7AQ%3D%3D"

```

but can I get actual location from this somehow?

**Comment by ReagentX** [comment]
From sent pins yes. The other type of message sends the same thing as sharing your location and includes an embed that shows your live location, which we can't really export. 

The query string part will be fixed, it's an iCloud link for the sharing request.
