### ISSUE TITLE
Estimated export size is incorrect

### ISSUE THREAD

**Issue by musa11971** [ReagentX/imessage-exporter#246]
When running 
```
imessage-exporter -f html -c efficient
```

The tool prints: `Estimated export size: 33.68 GB` (which could very well be correct)

However, when scoping the export to only 2024 (which should be *far* less), it still says the same:

`Estimated export size: 33.68 GB` 

It seems like the estimate is not taking into account the filtered dataset.

**Comment by ReagentX** [comment]
Closing because this is already disallowed in the app:

https://github.com/ReagentX/imessage-exporter/blob/2dc3d034bd5e64eb04306c167418989e2dac7651/imessage-exporter/src/app/options.rs#L141-L150

And the tests for this pass:

https://github.com/ReagentX/imessage-exporter/blob/2dc3d034bd5e64eb04306c167418989e2dac7651/imessage-exporter/src/app/options.rs#L469-L493
