### ISSUE TITLE
Release to Brew

### ISSUE THREAD

**Issue by ReagentX** [ReagentX/imessage-exporter#26]
`imessage-exporter.rb`:

```ruby
class ImessageExporter < Formula
  desc "Export MacOS iMessage data + run iMessage Diagnostics"
  homepage "https://github.com/ReagentX/imessage-exporter"
  url "https://github.com/ReagentX/imessage-exporter/archive/refs/tags/0.1.9.tar.gz"
  sha256 "033789e51e3621a74b19e4a5339f0e0b65c2d33b8c3e367a5f7fbd1cdfa642e7"
  license "GPL-3.0-or-later"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args(path: "imessage-exporter")
  end

  test do
    assert_equal "imessage is not a valid export type! Must be one of <txt, html>\n",
    shell_output("imessage-exporter -f imessage")
    assert_equal "Diagnostics are enabled; format is disallowed\n",
    shell_output("imessage-exporter -f txt -d")
    assert_equal "No export type selected, required by no-copy\n",
    shell_output("imessage-exporter -n")
    assert_equal "No export type selected, required by export-path\n",
    shell_output("imessage-exporter -o imessage")
    assert_equal "",
    shell_output("imessage-exporter -p imessage")
  end
end

```

**Comment by ReagentX** [comment]
Brew has some pesky requirements the repo needs to meet first:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1920666/211426787-5e9d7883-261b-45f9-ae9d-4cefc1993148.png">

**Comment by ReagentX** [comment]
Apparently, maintainers are not allowed to submit their own work. See the discussion here: https://github.com/Homebrew/homebrew-core/pull/120503

**Comment by chenrui333** [comment]
That is just an audit check, which can be re-considered.

**Comment by chenrui333** [comment]
besides that, any reason why closing the PR?

**Comment by cedricloneux** [comment]
> Brew has some pesky requirements the repo needs to meet first:
> 
> <img alt="image" width="585" src="https://user-images.githubusercontent.com/1920666/211426787-5e9d7883-261b-45f9-ae9d-4cefc1993148.png">

The requirements are for the case you want your formula to be available from brew core itself. But you can create a "tap", just as you can host your own repository on linux just by putting the formula file in the repository or another repo. That's what most projects do and give installation instruction in the main README.md

**Comment by cedricloneux** [comment]
It will be. I have enhanced the brew file btw.
I am still ready to provide it, with the CI/CD (GitHub actions) to automate it.

Following: https://github.com/ReagentX/imessage-exporter/pull/77#discussion_r1082658319
Since that time, have you had time to think about what I told you about the readme file structure and build setup ? I would greatly enhance the experience of repo's visitors and you release experience too.
- regular releases
- no need to build and move manually
- available via homebrew package manager
- brew file automatically updated at each release
- visitor know how to install at a glance and do it in a single command
