### ISSUE TITLE
Choose conversations to export

### ISSUE THREAD

**Issue by ReagentX** [ReagentX/imessage-exporter#61]
This came from feature request https://github.com/ReagentX/imessage-exporter/issues/51.

Right now, `imessage-exporter` exports every conversation it can see. It could be useful to specify specific conversation(s).

The easiest way to accomplish this is to know the `chat`'s ID in the table, but even that may not be correct due to the [duplication problem](https://github.com/ReagentX/imessage-exporter/blob/develop/docs/tables/duplicates.md). We can of course show this to the user, but selecting from a list in a reasonable manner is an interesting UX problem.

I don't want to emit a huge list and expect the user to read through it, there must be a way to live-search it.

**Comment by Debusan13** [comment]
I would think that a CLI option along the lines of `--people=first_last,first1_last1` would be dirty but get the job done. One library that might come in handy is [Rust Fuzzy Matcher](https://github.com/lotabout/fuzzy-matcher) though exact implementation would fall to you.

Maybe to make everyone's life easier, using the address book sources stored in `/Library/Application Support/AddressBook/Sources` would be the best bet. This directory has other subdirectories in it, the largest one contains all the contacts in `.abcdp` format which is just a database file. From here each chat could be labelled with contact names rather than the raw phone number.

For iOS backups (which I plan on making a larger issue report on) the contacts should be stored in `$iPhone_Backup/ '31' / '31bb7ba8914766d4ba40d6dfb6113c8b614be442'`. Again not the cleanest solution to hardcode it in but this is the equivalent to a "contacts.db" (Source: [iMessageBackup (python)](https://github.com/nprezant/iMessageBackup/blob/940d001fb7be557d5d57504eb26b3489e88de26e/imessage_backup_tools.py#L92))

Hope some of this additional research could help, I know you did a lot already so apologies if I'm retreading ground.

**Comment by toomim** [comment]
I'm encountering this, too. I'm glad there are folks looking into it!

**Comment by salexgit** [comment]
Hi

Good idea! 

Bear in mind that this feature might require solving the issue mentioned by me in #279. What I noticed that if a person has iMessage associated with a phone and email, or this association changed at some point, then same email thread will end up to different files with different names. Without solving that problem we will have the same problem here - it will be quite tricky to specify which thread should be exported.  

An idea of using /Library/Application Support/AddressBook/Sources looks Ok, but there can be even a simple contacts.txt file.

**Comment by punkhop** [comment]
Would absolutely love to be able to choose a single contact name/number/ID/anything unique so I can export only conversations with them, not every conversation with everyone.

**Comment by te5s3rakt** [comment]
just installed this for this specific reason, only to find it doesn't support single conversation export.

my iMessage library is massive, so don't really want to export everything only for a single conversation.

so for me for now, i'll keep hunting for a tool to solve my immediate need.

but this would be a huge +1 from me. definitely will be watching this repo :)

**Comment by thatcoleyouknow** [comment]
I see this is targeted for the next minor release but I want to add that I'd love to see support for this too. I would like to backup specific messages with specific people, either by phone number or email, so I don't have to backup all attachments for just a handful of conversations. 

@ReagentX - Please don't take this as a bribe but I'd like to contribute to this project as I know this takes time out of your personal life and this is invaluable to me. I looked at your profile and I don't see a way to tip you or buy you a beer. Do you have something you could share so I can say thank you in a little more than words?
